### ISSUE TITLE
V0.1 Roadmap

### ISSUE THREAD

**Issue by CameronLonsdale** [CameronLonsdale/lantern#9]
- [x] Make dynamicdict have appropriate behaviour for its name. not even a dict right now
- [x] Update the vigenere example text to showcase the diversity better. Investigate that bug why the hackers manifesto with punctuation didnt decrypt the first paragraph properly.
(Fixed! It was due to digits not being removed. Its a messy fix, but it works for now until I can build nicer abstractions in later updates)

- [x] Investigate speed, see if its possible to speed anything up
I think the speed is reasonable. 2 seconds for simple sub / vigenere. If I wanted speed I wouldnt use python. I made some small changes to free up some bottlenecks but Im pushing the limits of the language. I might investigate rewriting several key functions in a compiled language in the future

- [x] Investigate usability. See if alternating subsitution cipher code can be simplified and made intuitive
- [x] Update README to show python3.4 or newer is required (same for docs)
- [x] Review documentation to make sure its configured properly
- [x] Setup readthedocs for stable and development releases
- [x] Update version to 0.1 and upload to pypi

**Comment by CameronLonsdale** [comment]
comments so I see later
- Make combine_columns accept *args. 
- Think about improving the default corpus / Have different ones on hand...?

**Comment by CameronLonsdale** [comment]
Context managers for different languages? 
with language(french):
    caesar.decrypt(...)

**Comment by CameronLonsdale** [comment]
It's lit
